/RMG/Geometry/RegisterDetector Germanium germanium 001


/RMG/Geometry/SetMaxStepSize 0.2 um germanium

/RMG/Processes/SensitiveProductionCut 0.1 um

/run/initialize

# other settings
/RMG/Output/Germanium/Cluster/PreClusterOutputs
/RMG/Output/Germanium/Cluster/SetPreClusterDistance 1 um
/RMG/Output/Germanium/Cluster/CombineLowEnergyElectronTrack
/RMG/Output/Germanium/Cluster/RedistributeGammaEnergy

/RMG/Output/Germanium/StoreTrackID true

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume germanium

/RMG/Generator/Select GPS
/gps/particle ion
/gps/energy 0 eV
/gps/ion 88 224
/process/had/rdm/nucleusLimits 208 224 81 88

/run/beamOn {N}
